[Out]
port = 10

[Database]
name = "bells"
override_name = "bell_overrides"
admin = "admin"

[Rings]
length = 5
maxlength = 5
preparatory_length = 1
interval = 2
is_first_preparatory_enabled = true
are_all_preparatory_enabled = true
default = 0
auto = false

[Privileges]
owners = [ "newbell_admin",]
receivers = [ "1134602783",]

[Display]
delay = 3
port = 3

[Daemon]
delay = 1

[Misc]
status = "Последний запуск: 14.04.2023 22:01"
cli_mode = false
